export const RESOURCES = {
  PRODUCTS: 'products',
  ORDERS: 'orders',
  USERS: 'users',
  CATEGORIES: 'categories',
  ROLES: 'roles',
  PERMISSIONS: 'permissions',
  SYSTEM: 'system',
} as const;

export const ACTIONS = {
  CREATE: 'create',
  READ: 'read',
  UPDATE: 'update',
  DELETE: 'delete',
} as const;

export const PERMISSIONS = {
  // Users
  USERS_CREATE: `${RESOURCES.USERS}:${ACTIONS.CREATE}`,
  USERS_READ: `${RESOURCES.USERS}:${ACTIONS.READ}`,
  USERS_UPDATE: `${RESOURCES.USERS}:${ACTIONS.UPDATE}`,
  USERS_DELETE: `${RESOURCES.USERS}:${ACTIONS.DELETE}`,

  // Roles
  ROLES_CREATE: `${RESOURCES.ROLES}:${ACTIONS.CREATE}`,
  ROLES_READ: `${RESOURCES.ROLES}:${ACTIONS.READ}`,
  ROLES_UPDATE: `${RESOURCES.ROLES}:${ACTIONS.UPDATE}`,
  ROLES_DELETE: `${RESOURCES.ROLES}:${ACTIONS.DELETE}`,

  // Permissions
  PERMISSIONS_CREATE: `${RESOURCES.PERMISSIONS}:${ACTIONS.CREATE}`,
  PERMISSIONS_READ: `${RESOURCES.PERMISSIONS}:${ACTIONS.READ}`,
  PERMISSIONS_UPDATE: `${RESOURCES.PERMISSIONS}:${ACTIONS.UPDATE}`,
  PERMISSIONS_DELETE: `${RESOURCES.PERMISSIONS}:${ACTIONS.DELETE}`,

  // Products
  PRODUCTS_CREATE: `${RESOURCES.PRODUCTS}:${ACTIONS.CREATE}`,
  PRODUCTS_READ: `${RESOURCES.PRODUCTS}:${ACTIONS.READ}`,
  PRODUCTS_UPDATE: `${RESOURCES.PRODUCTS}:${ACTIONS.UPDATE}`,
  PRODUCTS_DELETE: `${RESOURCES.PRODUCTS}:${ACTIONS.DELETE}`,

  // Categories
  CATEGORIES_CREATE: `${RESOURCES.CATEGORIES}:${ACTIONS.CREATE}`,
  CATEGORIES_READ: `${RESOURCES.CATEGORIES}:${ACTIONS.READ}`,
  CATEGORIES_UPDATE: `${RESOURCES.CATEGORIES}:${ACTIONS.UPDATE}`,
  CATEGORIES_DELETE: `${RESOURCES.CATEGORIES}:${ACTIONS.DELETE}`,
} as const;
